/// Flutter icons AlgorandIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AlgorandIcons
///      fonts:
///       - asset: fonts/AlgorandIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class AlgorandIcons {
  AlgorandIcons._();

  static const _kFontFam = 'AlgorandIcons';
  static const String? _kFontPkg = null;

  static const IconData android = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoft_windows = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData linux = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ubuntu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debian = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData raspberry_pi = IconData(0xf7bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
